### ISSUE TITLE
Dupe/VoidBug

### ISSUE THREAD

**Issue by Speiger** [JDKDigital/euconverter#1]
LazyOptionals have a invalidation callback.
Sadly this block never actually calls it.

https://github.com/JDKDigital/euconverter/blob/37520215454da38699208e4de3c7d3de6b0b7dc0/src/main/java/cy/jdkdigital/euconverter/block/entity/ConverterBlockEntity.java#L24

Simply use the "onUnloaded" function from IC2Cs class you use and call "energyHandler.invalidate()" in there.

Also every time the facing is changed you need to invalidate the lazyOptional and recreate it.

**Comment by JaisDK** [comment]
should be fine now in the new version

**Comment by Speiger** [comment]
@JaisDK :)

I hope it is intentional when you rotate the machine it will void the entire RF buffer.
If that is intended then that's fine.

**Comment by JaisDK** [comment]
sure, totally intended :D, at least until next update
