### ISSUE TITLE
Doesn't work when storage is full.

### ISSUE THREAD

**Issue by gfbbkon** [JDKDigital/euconverter#2]
Problem: when you use an energy source and leave it to fill the EU converter, after filling it does not react in any way, even if you connect an energy storage from Industrial Craft 2 Classic to converter.
Sorry for my english, I'm just using google translator.

**Comment by JaisDK** [comment]
Can you show a screenshot of your setup?

**Comment by gfbbkon** [comment]
> Can you show a screenshot of your setup?

What setup are you talking about?

**Comment by JaisDK** [comment]
should be fine now in the new version

**Comment by gfbbkon** [comment]
> should be fine now in the new version

Tested, all working, thanks and have a nice day
