### ISSUE TITLE
(problem) Energy transfer from converter to converter.

### ISSUE THREAD

**Issue by gfbbkon** [JDKDigital/euconverter#4]
Problem: when you put several EU converters next to each other or connect them with a wire, they begin to transfer energy to each other. This is clearly visible if you connect them in front of the induction matrix (Mekanism) and/or connect them with super cable (Industrial Craft 2 Classic).

**Comment by JaisDK** [comment]
they transfer EU or FE to each other?

**Comment by gfbbkon** [comment]
> they transfer EU or FE to each other?

They only transport EU.
