### ISSUE TITLE
[Feature Request] Higher tier converters

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/euconverter#5]
Hi, I dont know if you're still actively working on this mod but it would be really useful if there were some post HV tier converters available, especially ev/iv and perhaps even luv. I wouldnt mind offering a pr to add them even if you accept that sorta thing. At anyrate, thanks for a great mod!

**Comment by JaisDK** [comment]
I wasn't planning any additional content, but I'll keep it updated when IC2C updates.

You're welcome to make PR with more converters if you're up for it. I only made the tiers that there are RF generators for.
